- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Run updates and upgrade packages
      apt:
        update_cache: yes
      changed_when: false

  roles:
    - role: geerlingguy.dotfiles
      vars:
        dotfiles_repo: "git@github.com:markdarwin/.dotfiles.git"
        dotfiles_repo_version: "main"
        dotfiles_files:
          - .zshrc

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/microsoft-packages.yml
    - include_tasks: tasks/configure-terminal.yml
