- hosts: localhost
  connection: local
  become: true
  pre_tasks:
    - name: Run updates and upgrade packages
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include: tasks/packages.yml
