- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Run updates and upgrade packages
      apt:
        update_cache: yes
      changed_when: false

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/microsoft-packages.yml
    - include_tasks: tasks/configure-terminal.yml

