- hosts: localhost
  connection: local
  become: true

  vars_files:
    - vault.yml

  pre_tasks:
    # 1. Install Fortinet key BEFORE any apt update
    - include_tasks: tasks/forticlient.yml
      tags: forticlient

    # 2. Now it's safe to update package cache (Debian or Fedora)
    - name: Update package cache (Debian)
      ansible.builtin.apt:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Update package cache (Fedora)
      ansible.builtin.dnf:
        update_cache: yes
      changed_when: false
      when: ansible_os_family == 'RedHat'

  roles:
    - role: geerlingguy.dotfiles
      vars:
        dotfiles_repo: "git@github.com:markdarwin/.dotfiles.git"
        dotfiles_repo_version: "main"
        dotfiles_files:
          - .zshrc
          - .zprofile
          - .config/alacritty

  tasks:
    - include_tasks: tasks/packages.yml
    - include_tasks: tasks/configure-terminal.yml
    - include_tasks: tasks/system-tweaks.yml
    - include_tasks: tasks/microsoft-packages.yml
    - include_tasks: tasks/vivaldi-browser.yml
    - include_tasks: tasks/terraform.yml
    - include_tasks: tasks/obsidian.yml
    - include_tasks: tasks/github-packages.yml
    - include_tasks: tasks/onedrive.yml
